SRC += source.c

MOUSEKEY_ENABLE = yes   
AUTO_SHIFT_ENABLE = yes 
CAPS_WORD_ENABLE = no   
SWAP_HANDS_ENABLE = no  
RGBLIGHT_ENABLE = yes   
RGB_MATRIX_ENABLE = no
OLED_ENABLE     = no
OLED_DRIVER     = SSD1306
VIA_ENABLE      = yes   
LTO_ENABLE      = yes
ENCODER_ENABLE  = yes   
ENCODER_MAP_ENABLE = no
